// <auto-generated />
using System;
using ImbuziSmart.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImbuziSmart.Server.Migrations
{
    [DbContext(typeof(ImbuziDbContext))]
    [Migration("20260416092219_AddIdentityAndTenants")]
    partial class AddIdentityAndTenants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImbuziSmart.Server.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ImbuziSmart.Server.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ImbuziSmart.Shared.Entities.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcquisitionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchasedFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<Guid?>("SireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Species")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Tag")
                        .IsUnique();

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Breed = "Boer",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2023, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Themba",
                            Notes = "Dominant buck. Excellent build, strong Boer genetics.",
                            Sex = 0,
                            Species = 0,
                            Status = 0,
                            Tag = "BK-001",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Breed = "Boer Cross",
                            CreatedAt = new DateTime(2025, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2023, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mandla",
                            Notes = "Young buck, good temperament. Ready for first breeding season.",
                            Sex = 0,
                            Species = 0,
                            Status = 0,
                            Tag = "BK-002",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Breed = "Boer",
                            CreatedAt = new DateTime(2025, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2022, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Nandi",
                            Notes = "Top producer — 3 successful kiddings. Always twins.",
                            Sex = 1,
                            Species = 0,
                            Status = 0,
                            Tag = "DE-001",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Breed = "Boer",
                            CreatedAt = new DateTime(2025, 9, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Lindiwe",
                            Notes = "Daughter of Themba. Currently pregnant — due soon.",
                            Sex = 1,
                            SireId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Species = 0,
                            Status = 0,
                            Tag = "DE-002",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Breed = "Indigenous Veld",
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Nomalusa",
                            Notes = "Hardy doe, good forager. First pregnancy.",
                            Sex = 1,
                            Species = 0,
                            Status = 0,
                            Tag = "DE-003",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Breed = "Boer",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DamId = new Guid("20000000-0000-0000-0000-000000000001"),
                            DateOfBirth = new DateTime(2023, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Thembi",
                            Notes = "Daughter of Nandi. Good maternal instincts.",
                            Sex = 1,
                            Species = 0,
                            Status = 0,
                            Tag = "DE-004",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Breed = "Savanna",
                            CreatedAt = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Zanele",
                            Notes = "White Savanna doe, heat observed recently.",
                            Sex = 1,
                            Species = 0,
                            Status = 0,
                            Tag = "DE-005",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Breed = "Boer",
                            CreatedAt = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DamId = new Guid("20000000-0000-0000-0000-000000000001"),
                            DateOfBirth = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sipho",
                            Notes = "Strong kid, growing well. Weaning approaching.",
                            Sex = 0,
                            SireId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Species = 0,
                            Status = 0,
                            Tag = "KD-001",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Breed = "Boer",
                            CreatedAt = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DamId = new Guid("20000000-0000-0000-0000-000000000001"),
                            DateOfBirth = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ayanda",
                            Notes = "Twin of Sipho. Slightly smaller but healthy.",
                            Sex = 1,
                            SireId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Species = 0,
                            Status = 0,
                            Tag = "KD-002",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Breed = "Boer Cross",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DamId = new Guid("20000000-0000-0000-0000-000000000004"),
                            DateOfBirth = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Busi",
                            Notes = "Weaned successfully. Ready for next phase.",
                            Sex = 1,
                            SireId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Species = 0,
                            Status = 0,
                            Tag = "KD-003",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Breed = "Indigenous Veld",
                            CreatedAt = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DamId = new Guid("20000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Lungile",
                            Notes = "Good weight, cleared withdrawal. Ready for market.",
                            Sex = 0,
                            Species = 0,
                            Status = 3,
                            Tag = "KD-004",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Breed = "Boer",
                            CreatedAt = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2024, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Lesedi",
                            Notes = "Sold at Vryburg auction — R3,200.",
                            Sex = 1,
                            Species = 0,
                            Status = 1,
                            Tag = "DE-006",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("ImbuziSmart.Shared.Entities.CostEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("AnimalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AnimalId");

                    b.ToTable("CostEntries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            Amount = 1200.00m,
                            Category = 0,
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lucerne bales x 20 — monthly feed supply",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000002"),
                            Amount = 450.00m,
                            Category = 0,
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Maize meal 50kg bag — supplementary feeding for pregnant does",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000003"),
                            Amount = 280.00m,
                            Category = 0,
                            CreatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mineral lick blocks x 4",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000004"),
                            Amount = 350.00m,
                            AnimalId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Category = 3,
                            CreatedAt = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dr. Mokoena — foot rot treatment and hoof trim",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000005"),
                            Amount = 180.00m,
                            AnimalId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Category = 3,
                            CreatedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dr. Mokoena — scours treatment for Sipho",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000006"),
                            Amount = 520.00m,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ivermectin 500ml, Pulpy Kidney Vaccine x 20 doses — quarterly stock",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000007"),
                            Amount = 2000.00m,
                            Category = 2,
                            CreatedAt = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sbusiso — monthly herding and general farm labor",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000008"),
                            Amount = 2000.00m,
                            Category = 2,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sbusiso — monthly herding and general farm labor",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000009"),
                            Amount = 850.00m,
                            Category = 4,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ear tag applicator + 50 tags",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000010"),
                            Amount = 600.00m,
                            AnimalId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Category = 0,
                            CreatedAt = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fattening feed for Lesedi before auction",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("ImbuziSmart.Shared.Entities.FarmSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("ZAR");

                    b.Property<bool>("EnableHeatTracking")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableInbreedingCheck")
                        .HasColumnType("bit");

                    b.Property<bool>("EnablePushNotifications")
                        .HasColumnType("bit");

                    b.Property<int>("HeatAlertDaysBefore")
                        .HasColumnType("int");

                    b.Property<int>("HeatCycleDays")
                        .HasColumnType("int");

                    b.Property<int>("KiddingWatchDaysBefore")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotifyHeatCycle")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyKiddingWatch")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyWeaning")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyWithdrawalExpiry")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("FarmSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "ZAR",
                            EnableHeatTracking = true,
                            EnableInbreedingCheck = true,
                            EnablePushNotifications = false,
                            HeatAlertDaysBefore = 2,
                            HeatCycleDays = 21,
                            KiddingWatchDaysBefore = 5,
                            NotifyHeatCycle = true,
                            NotifyKiddingWatch = true,
                            NotifyWeaning = true,
                            NotifyWithdrawalExpiry = true,
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("ImbuziSmart.Shared.Entities.HeatRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Intensity")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ObservedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Signs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AnimalId");

                    b.ToTable("HeatRecords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            AnimalId = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Intensity = 1,
                            ObservedDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Signs = "Flagging tail, frequent vocalization, mounting other does",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            AnimalId = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Intensity = 0,
                            ObservedDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Signs = "Mild flagging, slight swelling",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            AnimalId = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Intensity = 2,
                            ObservedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Signs = "Standing heat, accepted buck",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            AnimalId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Intensity = 1,
                            ObservedDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Signs = "Restless, vocalizing, swollen vulva",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("ImbuziSmart.Shared.Entities.MatingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualKiddingDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BuckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DoeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MatingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DoeId", "MatingDate");

                    b.ToTable("MatingRecords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            ActualKiddingDate = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            BuckId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 8, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoeId = new Guid("20000000-0000-0000-0000-000000000001"),
                            MatingDate = new DateTime(2025, 8, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Twins born — both healthy. Sipho (male) and Ayanda (female).",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            BuckId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoeId = new Guid("20000000-0000-0000-0000-000000000002"),
                            MatingDate = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "First mating for Mandla. Lindiwe showing signs of nearing kidding.",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            BuckId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoeId = new Guid("20000000-0000-0000-0000-000000000003"),
                            MatingDate = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "First pregnancy for Nomalusa. Progressing well.",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            ActualKiddingDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            BuckId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DoeId = new Guid("20000000-0000-0000-0000-000000000004"),
                            MatingDate = new DateTime(2025, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Single kid born — Busi (female). Easy delivery.",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
                        });
                });

            modelBuilder.Entity("ImbuziSmart.Shared.Entities.MedicalLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TreatmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WithdrawalPeriodDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AnimalId");

                    b.ToTable("MedicalLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            AnimalId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dosage = "1ml per 10kg body weight",
                            Medication = "Ivermectin",
                            Notes = "Routine quarterly deworming. Withdrawal period expired.",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            TreatmentDate = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            VetName = "Dr. Mokoena",
                            WithdrawalPeriodDays = 35
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            AnimalId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dosage = "1ml per 5kg",
                            Medication = "Sulfadimidine",
                            Notes = "Mild scours, responding well to treatment.",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            TreatmentDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VetName = "Dr. Mokoena",
                            WithdrawalPeriodDays = 14
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            AnimalId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dosage = "2ml subcutaneous",
                            Medication = "Pulpy Kidney Vaccine",
                            Notes = "Annual Clostridial vaccination. No withdrawal required.",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            TreatmentDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000004"),
                            AnimalId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dosage = "1ml per 10kg IM",
                            Medication = "Oxytetracycline LA",
                            Notes = "Mild foot rot on front left. Hoof trimmed and treated.",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            TreatmentDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            VetName = "Dr. Mokoena",
                            WithdrawalPeriodDays = 14
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000005"),
                            AnimalId = new Guid("30000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dosage = "5ml oral",
                            Medication = "Albendazole",
                            Notes = "Pre-market deworming. Withdrawal period cleared.",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            TreatmentDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            WithdrawalPeriodDays = 14
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000006"),
                            AnimalId = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dosage = "2ml IM",
                            Medication = "Vitamin ADE Injection",
                            Notes = "Pre-kidding vitamin boost. No withdrawal.",
                            TenantId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            TreatmentDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ImbuziSmart.Shared.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("ImbuziSmart.Shared.Entities.WeightRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("BodyLengthCm")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HeartGirthCm")
                        .HasColumnType("float");

                    b.Property<double>("Kilograms")
                        .HasColumnType("float");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Scale");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WeighedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AnimalId");

                    b.ToTable("WeightRecords");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ImbuziSmart.Server.Identity.AppUser", b =>
                {
                    b.HasOne("ImbuziSmart.Shared.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ImbuziSmart.Server.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ImbuziSmart.Server.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ImbuziSmart.Server.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ImbuziSmart.Server.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImbuziSmart.Server.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ImbuziSmart.Server.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
